package Books.StepsInScala_Loverdos.chapter11_Trees.iter.node.iterableProvider

import Books.StepsInScala_Loverdos.chapter9_FilesForTraversable.file.NativeFile


object NativeChildrenProvider extends VFileChildrenProvider[NativeFile]
