package Loverdos_StepsInScala.chapter11_Trees.iter.node.iterableProvider

import Loverdos_StepsInScala.chapter9_FilesForTraversable.file.NativeFile


object NativeChildrenProvider extends VFileChildrenProvider[NativeFile]
